services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  data_load:
    build:
      context: src/data_load
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy

  data_quality:
    build:
      context: src/data_quality_analysis
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      data_load:
        condition: service_completed_successfully

  data_research:
    build:
      context: src/data_research
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      data_load:
        condition: service_completed_successfully

  visualization:
    build:
      context: src/visualization
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./reports:/app/reports
    depends_on:
      data_research:
        condition: service_completed_successfully

  web:
    build:
      context: src/web
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
    depends_on:
      visualization:
        condition: service_completed_successfully


volumes:
  db_data:
  reports:

networks:
  default:
    name: analytics_network