apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: analytics-app
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 4
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
      - name: web
        image: daniilshevch/app-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_DATABASE
          value: "analytics_db"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        volumeMounts:
        - name: reports
          mountPath: /app/reports
      volumes:
      - name: reports
        persistentVolumeClaim: { claimName: reports-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: analytics-app
spec:
  selector: { app: web }
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31666  
  type: NodePort     